version: '3.7'

services:
    backend:
        build: ./API2/
        ports:
            - 8080:80
        networks:
            - app-network
        depends_on:
            - database

    database:
        build: ./postgres/
        image: postgres:14.1-alpine
        environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pwd
        ports:
            - 5432:5432
        networks:
            - app-network

    httpd:
        build: ./http/
        ports:
            - 80:80
        networks:
            - app-network
        depends_on:
            - backend

networks:
    app-network:
        driver: bridge