version: '3.3'
services:
  backend:
    container_name: backend
    build: ./API2/
    networks:
      - app-network
    depends_on:
      - database

  database:
    container_name: database
    restart: always
    build: ./postgres/
    networks:
      - app-network
    env_file:
      - postgres/env

  httpd:
    container_name: reverse_proxy
    build: ./http/
    ports:
      - "80:80"
    networks:
      - app-network


volumes:
  my_db_volume:
    driver: bridge

networks:
  app-network:
    driver: bridge